spring.application.name=Gundi

logging.level.org=WARN
# logging.level.org.springframework.security=DEBUG

spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://${db_host}:${db_port}/__gundi?createDatabaseIfNotExist=true

# spring.jpa.properties.hibernate.format_sql = true
# spring.jpa.properties.hibernate.use_sql_comments = true
# spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.mail.username=${mail_username}
spring.mail.password=${mail_password}
spring.mail.host=${mail_host}
spring.mail.port=${mail_port}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.fallback.timeframe_hours=48
app.fallback.mail.from=noreply@gundi.com
app.fallback.mail.display_name=Gundi
app.fallback.mail.subject=Confirm your email address
app.fallback.mail.is_html=true
app.fallback.token.expiration_minutes=15
app.fallback.token.use_link=false
app.fallback.token.length=6
app.fallback.token.allowed_characters=\
    1, 2, 3, 4, 5, 6, 7, 8, 9, 0

app.new_user.timeframe_hours=${app.fallback.timeframe_hours}
app.new_user.mail.from=${app.fallback.mail.from}
app.new_user.mail.display_name=${app.fallback.mail.display_name}
app.new_user.mail.subject=${app.fallback.mail.subject}
app.new_user.mail.is_html=${app.fallback.mail.is_html}
app.new_user.token.expiration_minutes=${app.fallback.token.expiration_minutes}
app.new_user.token.use_link=${app.fallback.token.use_link}
app.new_user.token.length=${app.fallback.token.length}
app.new_user.token.allowed_characters=${app.fallback.token.allowed_characters}